version: '3.2'

services:
  monolith:
    build: monolith
    ports:
      - 8000:8000
    volumes:
      - ./monolith:/app
  microservice:
    build: microservice
    ports:
      - 3000:3000
    volumes:
      - ./microservice:/app
  reverse-proxy:
    build: reverse-proxy
    ports:
      - 5000:5000
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
  # scope:
  #   image: weaveworks/scope:1.10.2
  #   network_mode: "host"
  #   pid: "host"
  #   privileged: true
  #   labels:
  #     - "works.weave.role=system"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:rw"
  #   command:
  #     - "--probe.docker=true"
